modules_dir = "artifacts/"

[[module]]
    name = "ipfs_effector"
    mem_pages_count = 100
    logger_enabled = true

    [module.mounted_binaries]
    ipfs = "/usr/local/bin/ipfs"
    bash = "/usr/bin/bash"
    curl = "/usr/bin/curl"

    [module.wasi]
     envs = { "/tmp/vault" = "/tmp" }

[[module]]
    name = "ipfs_pure"
    mem_pages_count = 100
    logger_enabled = true
